'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Goods', [
      {
        name: "Джинсы Levi's 511",
        slug: 'levis-511-jeans',
        description: 'Классические slim джинсы из денима',
        price: 5999,
        sku: 'LV001',
        category_id: 1,
        brand_id: 2,
        quantity: 15,
        image: JSON.stringify([
          'https://lscoecomm.scene7.com/is/image/lscoecomm/TAPERED%20JEANS?fmt=jpeg&qlt=70&resMode=sharp2&fit=crop,1&op_usm=0.6,0.6,8&wid=1200&hei=1500',
        ]),
        features: JSON.stringify({
          material: '99% хлопок, 1% эластан',
          color: 'Синий',
          sizes: ['28x30', '30x30', '32x30', '34x30'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Куртка Adidas Originals',
        slug: 'adidas-originals-jacket',
        description: 'Стильная ветровка с классическим дизайном',
        price: 7999,
        sku: 'AD001',
        category_id: 1,
        brand_id: 2,
        quantity: 12,
        image: JSON.stringify([
          'https://main-cdn.sbermegamarket.ru/big1/hlr-system/356/101/314/426/204/5/100051716731b0.jpg',
        ]),
        features: JSON.stringify({
          material: '100% нейлон',
          color: 'Черный',
          sizes: ['S', 'M', 'L', 'XL'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Рубашка Zara Slim Fit',
        slug: 'zara-slim-fit-shirt',
        description: 'Элегантная рубашка slim fit',
        price: 2999,
        sku: 'ZR001',
        category_id: 1,
        brand_id: 3,
        quantity: 20,
        image: JSON.stringify([
          'https://static.zara.net/assets/public/edc6/d744/4bdc48138312/bbcb1dca2e87/06580131250-a1/06580131250-a1.jpg?ts=1725616628390',
        ]),
        features: JSON.stringify({
          material: '100% хлопок',
          color: 'Белый',
          sizes: ['S', 'M', 'L', 'XL'],
          care: 'Машинная стирка при 40°C',
        }),
      },
      {
        name: 'Футболка Uniqlo Airism',
        slug: 'uniqlo-airism-t-shirt',
        description: 'Легкая футболка с технологией Airism',
        price: 1499,
        sku: 'UQ001',
        category_id: 1,
        brand_id: 5,
        quantity: 30,
        image: JSON.stringify(['https://japan.com.ua/upload/iblock/51f/00_414056.jpg']),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Белый',
          sizes: ['S', 'M', 'L', 'XL'],
          care: 'Машинная стирка при 30°C',
        }),
      },

      // Женская одежда (category_id: 2)
      {
        name: 'Платье Zara Floral',
        slug: 'zara-floral-dress',
        description: 'Летнее платье с цветочным принтом',
        price: 3999,
        sku: 'ZR002',
        category_id: 2,
        brand_id: 3,
        quantity: 14,
        image: JSON.stringify([
          'https://static.zara.net/assets/public/1c80/8dee/7b904324a072/f91aa71cc1c1/08730111330-p/08730111330-p.jpg?ts=1754557814678&w=744&f=auto',
        ]),
        features: JSON.stringify({
          material: '100% вискоза',
          color: 'Цветочный',
          sizes: ['XS', 'S', 'M', 'L'],
          care: 'Ручная стирка',
        }),
      },
      {
        name: 'Юбка H&M Midi',
        slug: 'hm-midi-skirt',
        description: 'Элегантная миди-юбка',
        price: 2499,
        sku: 'HM002',
        category_id: 2,
        brand_id: 4,
        quantity: 18,
        image: JSON.stringify([
          'https://ireland.apollo.olxcdn.com/v1/files/khqtdaqomojx-UA/image;s=708x1000',
        ]),
        features: JSON.stringify({
          material: '100% хлопок',
          color: 'Черный',
          sizes: ['XS', 'S', 'M', 'L'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Блузка Zara Silk',
        slug: 'zara-silk-blouse',
        description: 'Шелковая блузка для офиса',
        price: 4599,
        sku: 'ZR003',
        category_id: 2,
        brand_id: 3,
        quantity: 10,
        image: JSON.stringify([
          'https://image-thumbs.shafastatic.net/2186523709_310_430',
        ]),
        features: JSON.stringify({
          material: '100% шелк',
          color: 'Бежевый',
          sizes: ['XS', 'S', 'M', 'L'],
          care: 'Химчистка',
        }),
      },
      {
        name: "Джинсы Levi's 721",
        slug: 'levis-721-jeans',
        description: 'Женские джинсы slim fit',
        price: 5499,
        sku: 'LV002',
        category_id: 2,
        brand_id: 2,
        quantity: 16,
        image: JSON.stringify([
          'https://stockmann.ru/pi/pp/444/4831444/4831444-01.jpg@jpg',
        ]),
        features: JSON.stringify({
          material: '98% хлопок, 2% эластан',
          color: 'Черный',
          sizes: ['26x30', '28x30', '30x30', '32x30'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Куртка Nike Sportswear',
        slug: 'nike-sportswear-jacket',
        description: 'Спортивная куртка для активного отдыха',
        price: 6999,
        sku: 'NK002',
        category_id: 2,
        brand_id: 1,
        quantity: 8,
        image: JSON.stringify([
          'https://www.salesscanner.ru/wp-content/uploads/2021/08/kurtka-iz-sinteticheskogo-meha-sportswear-qwxfcr.jpg',
        ]),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Розовый',
          sizes: ['XS', 'S', 'M', 'L'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Футболка Uniqlo U',
        slug: 'uniqlo-u-t-shirt',
        description: 'Базовая футболка премиум качества',
        price: 1299,
        sku: 'UQ002',
        category_id: 2,
        brand_id: 5,
        quantity: 22,
        image: JSON.stringify([
          'https://a.lmcdn.ru/product/R/T/RTLABW761101_17824813_1_v2_2x.jpg',
        ]),
        features: JSON.stringify({
          material: '100% хлопок',
          color: 'Белый',
          sizes: ['XS', 'S', 'M', 'L'],
          care: 'Машинная стирка при 30°C',
        }),
      },

      // Детская одежда (category_id: 3)
      {
        name: 'Комплект H&M Kids',
        slug: 'hm-kids-set',
        description: 'Яркий комплект для активного отдыха',
        price: 1999,
        sku: 'HM003',
        category_id: 3,
        brand_id: 4,
        quantity: 20,
        image: JSON.stringify([
          'https://ir.ozone.ru/s3/multimedia-1-c/c1000/6951575964.jpg',
        ]),
        features: JSON.stringify({
          material: '100% хлопок',
          color: 'Синий',
          sizes: ['104', '110', '116', '122'],
          care: 'Машинная стирка при 40°C',
        }),
      },
      {
        name: 'Футболка Nike Kids',
        slug: 'nike-kids-t-shirt',
        description: 'Детская футболка с логотипом Nike',
        price: 1799,
        sku: 'NK003',
        category_id: 3,
        brand_id: 1,
        quantity: 25,
        image: JSON.stringify([
          'https://www.football-mania.ru/f/product/dc7794_657_4_web.jpg',
        ]),
        features: JSON.stringify({
          material: '100% хлопок',
          color: 'Красный',
          sizes: ['92', '98', '104', '110'],
          care: 'Машинная стирка при 40°C',
        }),
      },
      {
        name: 'Кепка New Era',
        slug: 'new-era-cap',
        description: 'Бейсболка премиум качества',
        price: 2499,
        sku: 'NE001',
        category_id: 4,
        brand_id: 1,
        quantity: 30,
        image: JSON.stringify([
          'https://usmall.ru/image/663/64/85/512881955dfad471469ea2ee44f11132.png',
        ]),
        features: JSON.stringify({
          material: '100% хлопок',
          color: 'Черный',
          sizes: ['Универсальный'],
          care: 'Ручная стирка',
        }),
      },
      {
        name: 'Рюкзак Nike Heritage',
        slug: 'nike-heritage-backpack',
        description: 'Стильный рюкзак для повседневного использования',
        price: 4499,
        sku: 'NK004',
        category_id: 4,
        brand_id: 1,
        quantity: 15,
        image: JSON.stringify([
          'https://www.weekend.ee/media/catalog/product/cache/f9e0d9020e92b085f189928719767c5c/e/l/el20221000-16.jpg',
        ]),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Черный',
          sizes: ['Один размер'],
          care: 'Протирать влажной тканью',
        }),
      },
      {
        name: 'Сумка Adidas Tote',
        slug: 'adidas-tote-bag',
        description: 'Вместительная сумка-шопер',
        price: 1999,
        sku: 'AD003',
        category_id: 4,
        brand_id: 2,
        quantity: 20,
        image: JSON.stringify([
          'https://www.forbox.com.ua/image/cache/data/tovary/aksessuary/adidas/sumki/adiacc040j/adiacc040j_blue_305-750x750.jpg',
        ]),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Синий',
          sizes: ['Один размер'],
          care: 'Протирать влажной тканью',
        }),
      },
      {
        name: 'Ремень Zara Leather',
        slug: 'zara-leather-belt',
        description: 'Кожаный ремень классический',
        price: 1499,
        sku: 'ZR005',
        category_id: 4,
        brand_id: 3,
        quantity: 25,
        image: JSON.stringify([
          'https://static.zara.net/assets/public/7ed0/2f73/0a8d44e98916/2ecb6c5ce83c/02823413716-a1/02823413716-a1.jpg?ts=1747840203849&w=744&f=auto',
        ]),
        features: JSON.stringify({
          material: '100% натуральная кожа',
          color: 'Коричневый',
          sizes: ['85', '90', '95', '100'],
          care: 'Использовать крем для кожи',
        }),
      },
      {
        name: 'Шарф H&M Wool',
        slug: 'hm-wool-scarf',
        description: 'Теплый шерстяной шарф',
        price: 1299,
        sku: 'HM004',
        category_id: 4,
        brand_id: 4,
        quantity: 28,
        image: JSON.stringify([
          'https://encrypted-tbn0.gstatic.com/image?q=tbn:ANd9GcTCO4KoHetzgWdPl6HyzlYoeDNDk4DM9KXl4A&s',
        ]),
        features: JSON.stringify({
          material: '80% шерсть, 20% акрил',
          color: 'Серый',
          sizes: ['Один размер'],
          care: 'Ручная стирка',
        }),
      },
      {
        name: 'Перчатки Uniqlo Heattech',
        slug: 'uniqlo-heattech-gloves',
        description: 'Теплые перчатки с технологией Heattech',
        price: 999,
        sku: 'UQ004',
        category_id: 4,
        brand_id: 5,
        quantity: 35,
        image: JSON.stringify([
          'https://img.joomcdn.net/19b80dd65bf8c6f3f10c02be5f0c2fa23cb3961b_original.jpeg',
        ]),
        features: JSON.stringify({
          material: '46% акрил, 29% полиэстер, 25% нейлон',
          color: 'Черный',
          sizes: ['Универсальный'],
          care: 'Ручная стирка',
        }),
      },
      {
        name: 'Шорты Adidas Training',
        slug: 'adidas-training-shorts',
        description: 'Спортивные шорты для тренировок',
        price: 2799,
        sku: 'AD004',
        category_id: 1,
        brand_id: 2,
        quantity: 22,
        image: JSON.stringify([
          'https://encrypted-tbn0.gstatic.com/image?q=tbn:ANd9GcSMsuGHMFOVtu-IwDNhWFj-qH0hKGk5wTKuWw&s',
        ]),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Синий',
          sizes: ['S', 'M', 'L', 'XL'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Пиджак Zara Blazer',
        slug: 'zara-blazer',
        description: 'Классический пиджак для офиса',
        price: 6999,
        sku: 'ZR006',
        category_id: 1,
        brand_id: 3,
        quantity: 8,
        image: JSON.stringify([
          'https://main-cdn.sbermegamarket.ru/big1/hlr-system/-75/667/669/212/620/42/100047647412b0.jpg',
        ]),
        features: JSON.stringify({
          material: '70% шерсть, 30% полиэстер',
          color: 'Синий',
          sizes: ['S', 'M', 'L', 'XL'],
          care: 'Химчистка',
        }),
      },
      {
        name: 'Кардиган H&M Knit',
        slug: 'hm-knit-cardigan',
        description: 'Теплый вязаный кардиган',
        price: 3499,
        sku: 'HM005',
        category_id: 2,
        brand_id: 4,
        quantity: 16,
        image: JSON.stringify([
          'https://image.hm.com/assets/hm/ff/70/ff70d7e595a6b7035d26809ea7bc6fa571162391.jpg?imwidth=2160',
        ]),
        features: JSON.stringify({
          material: '100% акрил',
          color: 'Бежевый',
          sizes: ['XS', 'S', 'M', 'L'],
          care: 'Ручная стирка',
        }),
      },
      {
        name: 'Пальто Uniqlo Ultra Light',
        slug: 'uniqlo-ultra-light-coat',
        description: 'Легкое пальто для демисезона',
        price: 7999,
        sku: 'UQ005',
        category_id: 2,
        brand_id: 5,
        quantity: 10,
        image: JSON.stringify([
          'https://obzorpokupok.ru/wp-content/uploads/2021/01/obzor-uniqlo-women-winter-jacket-review008.jpg',
        ]),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Бежевый',
          sizes: ['XS', 'S', 'M', 'L'],
          care: 'Химчистка',
        }),
      },
      {
        name: 'Кроссовки Nike Kids',
        slug: 'nike-kids-sneakers',
        description: 'Детские кроссовки для активных игр',
        price: 3999,
        sku: 'NK006',
        category_id: 3,
        brand_id: 1,
        quantity: 15,
        image: JSON.stringify([
          'https://marcos.com.ua/image/cache/3034019139_detskie-krossovki-nike-680x630.jpg',
        ]),
        features: JSON.stringify({
          material: 'Текстиль, синтетика',
          color: 'Синий',
          sizes: ['28', '29', '30', '31'],
          care: 'Протирать влажной тканью',
        }),
      },
      {
        name: 'Футболка Nike Dry',
        slug: 'nike-dry-academy',
        description: 'Футболка для футбольных тренировок',
        price: 2799,
        sku: 'NK007',
        category_id: 1,
        brand_id: 1,
        quantity: 18,
        image: JSON.stringify([
          'https://encrypted-tbn0.gstatic.com/image?q=tbn:ANd9GcTVntyGokGMHoP0aBBj3B8FhOR4pg_rl8pDcw&s',
        ]),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Белый',
          sizes: ['S', 'M', 'L', 'XL'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Штаны Adidas Tiro',
        slug: 'adidas-tiro-pants',
        description: 'Спортивные штаны для тренировок',
        price: 4499,
        sku: 'AD006',
        category_id: 1,
        brand_id: 2,
        quantity: 16,
        image: JSON.stringify([
          'https://cdn.sportmaster.ru/upload/mdm/media_content/resize/544/768_1024_85a6/74017800299.jpg',
        ]),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Черный',
          sizes: ['S', 'M', 'L', 'XL'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Рубашка Zara Linen',
        slug: 'zara-linen-shirt',
        description: 'Льняная рубашка для лета',
        price: 3599,
        sku: 'ZR008',
        category_id: 1,
        brand_id: 3,
        quantity: 12,
        image: JSON.stringify([
          'https://static.zara.net/assets/public/1a6d/ad69/082c4822bc94/40497b2ba567/04024159643-a1/04024159643-a1.jpg?ts=1751011681612',
        ]),
        features: JSON.stringify({
          material: '100% лен',
          color: 'Бежевый',
          sizes: ['S', 'M', 'L', 'XL'],
          care: 'Ручная стирка',
        }),
      },
      {
        name: 'Джинсы H&M Slim',
        slug: 'hm-slim-jeans',
        description: 'Слим джинсы современного кроя',
        price: 2999,
        sku: 'HM007',
        category_id: 1,
        brand_id: 4,
        quantity: 20,
        image: JSON.stringify([
          'https://dynamic.zacdn.com/J9jsImuZHN_ELB5a3eBVh931mdQ=/filters:quality(70):format(webp)/https://static-my.zacdn.com/p/hm-7415-7247423-1.jpg',
        ]),
        features: JSON.stringify({
          material: '98% хлопок, 2% эластан',
          color: 'Темно-синий',
          sizes: ['30x30', '32x30', '34x30', '36x30'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Футболка Uniqlo Supima',
        slug: 'uniqlo-supima-cotton',
        description: 'Футболка из хлопка премиум качества',
        price: 1499,
        sku: 'UQ007',
        category_id: 1,
        brand_id: 5,
        quantity: 28,
        image: JSON.stringify([
          'https://encrypted-tbn0.gstatic.com/image?q=tbn:ANd9GcQf_IFaMesAWm6VrNE1r_0WDn9-KtCGkRhSyg&s',
        ]),
        features: JSON.stringify({
          material: '100% хлопок Supima',
          color: 'Серый',
          sizes: ['S', 'M', 'L', 'XL'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Платье H&M Midi',
        slug: 'hm-midi-dress',
        description: 'Элегантное миди-платье',
        price: 3299,
        sku: 'HM008',
        category_id: 2,
        brand_id: 4,
        quantity: 14,
        image: JSON.stringify([
          'https://image.hm.com/assets/hm/c2/94/c2946ae20467534ab36ae65056f9b02a5465ace2.jpg?imwidth=2160',
        ]),
        features: JSON.stringify({
          material: '100% вискоза',
          color: 'Зеленый',
          sizes: ['XS', 'S', 'M', 'L'],
          care: 'Ручная стирка',
        }),
      },
      {
        name: 'Леггинсы Adidas Training',
        slug: 'adidas-training-leggings',
        description: 'Спортивные леггинсы для фитнеса',
        price: 3799,
        sku: 'AD007',
        category_id: 2,
        brand_id: 2,
        quantity: 18,
        image: JSON.stringify([
          'https://img2.ans-media.com/i/840x1260/SS24-LGD01T-99X_F1.jpg?v=1699466582',
        ]),
        features: JSON.stringify({
          material: '88% полиэстер, 12% эластан',
          color: 'Черный',
          sizes: ['XS', 'S', 'M', 'L'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Комплект Nike Kids',
        slug: 'nike-kids-set',
        description: 'Спортивный комплект для детей',
        price: 3299,
        sku: 'NK009',
        category_id: 3,
        brand_id: 1,
        quantity: 22,
        image: JSON.stringify([
          'https://admin.di-sport.uz/storage/thumbnails/galleries/20601/hWlB0FUXKBgcUDWbSvfmeojPJELW87QQCCgPAYgk-large.webp',
        ]),
        features: JSON.stringify({
          material: '100% хлопок',
          color: 'Синий',
          sizes: ['104', '110', '116', '122'],
          care: 'Машинная стирка при 40°C',
        }),
      },
      {
        name: 'Куртка Adidas Kids Winter',
        slug: 'adidas-kids-winter-jacket',
        description: 'Теплая зимняя куртка для детей',
        price: 5999,
        sku: 'AD008',
        category_id: 3,
        brand_id: 2,
        quantity: 10,
        image: JSON.stringify([
          'https://cdn.media.amplience.net/i/frasersdev/56022791_o?fmt=auto&upscale=false&w=767&h=767&sm=scaleFit&$h-ttl$',
        ]),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Красный',
          sizes: ['104', '110', '116', '122'],
          care: 'Машинная стирка при 30°C',
        }),
      },
      {
        name: 'Платье Zara Kids Party',
        slug: 'zara-kids-party-dress',
        description: 'Нарядное платье для праздников',
        price: 3199,
        sku: 'ZR010',
        category_id: 3,
        brand_id: 3,
        quantity: 12,
        image: JSON.stringify([
          'https://ir.ozone.ru/s3/multimedia-5/c1000/6739551509.jpg',
        ]),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Розовый',
          sizes: ['92', '98', '104', '110'],
          care: 'Ручная стирка',
        }),
      },
      {
        name: 'Рюкзак H&M Kids',
        slug: 'hm-kids-backpack',
        description: 'Яркий рюкзак для школьников',
        price: 1799,
        sku: 'HM009',
        category_id: 4,
        brand_id: 4,
        quantity: 25,
        image: JSON.stringify([
          'https://encrypted-tbn0.gstatic.com/image?q=tbn:ANd9GcRTdpECDWYx7TJ5NhPA5Kx1sQ0MFm1pNUOyFQ&s',
        ]),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Синий',
          sizes: ['Один размер'],
          care: 'Протирать влажной тканью',
        }),
      },
      {
        name: 'Кроссовки Uniqlo Kids',
        slug: 'uniqlo-kids-sneakers',
        description: 'Удобные кроссовки для детей',
        price: 2999,
        sku: 'UQ009',
        category_id: 3,
        brand_id: 5,
        quantity: 18,
        image: JSON.stringify([
          'https://ir.ozone.ru/s3/multimedia-1-g/c400/7521158320.jpg',
        ]),
        features: JSON.stringify({
          material: 'Текстиль, синтетика',
          color: 'Белый',
          sizes: ['28', '29', '30', '31'],
          care: 'Протирать влажной тканью',
        }),
      },
      {
        name: 'Сумка Nike Utility',
        slug: 'nike-utility-bag',
        description: 'Функциональная сумка для спорта',
        price: 3799,
        sku: 'NK010',
        category_id: 4,
        brand_id: 1,
        quantity: 15,
        image: JSON.stringify([
          'https://static.ftshp.digital/img/p/1/2/4/7/5/6/6/1247566-full_product.jpg',
        ]),
        features: JSON.stringify({
          material: '100% нейлон',
          color: 'Черный',
          sizes: ['Один размер'],
          care: 'Протирать влажной тканью',
        }),
      },
      {
        name: 'Ремень Adidas Webbing',
        slug: 'adidas-webbing-belt',
        description: 'Спортивный ремень из тесьмы',
        price: 1299,
        sku: 'AD009',
        category_id: 4,
        brand_id: 2,
        quantity: 30,
        image: JSON.stringify(['https://a.lmcdn.ru/product/A/D/AD093DUBKA65_1.jpg']),
        features: JSON.stringify({
          material: '100% полиэстер',
          color: 'Черный',
          sizes: ['S', 'M', 'L'],
          care: 'Протирать влажной тканью',
        }),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Goods', null, {});
  },
};
